import os
import pandas as pd
import matplotlib.pyplot as plt
import requests
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
import glob
import time

# 1. SETUP CONFIG (Hugging Face Free Tier)
# We use Mistral-7B because it is free and smart enough for policy summaries.
HF_TOKEN = os.environ.get("HF_TOKEN")
HF_API_URL = "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.3"

# Email Config (Gmail App Password)
RECIPIENT_EMAIL = "reezaaalarafat@gmail.com"
SENDER_EMAIL = os.environ.get("SENDER_EMAIL")
GMAIL_PASSWORD = os.environ.get("GMAIL_APP_PASSWORD")

def query_huggingface(prompt):
    """
    Sends the prompt to the free Hugging Face Inference API.
    """
    headers = {"Authorization": f"Bearer {HF_TOKEN}"}
    payload = {
        "inputs": f"<s>[INST] {prompt} [/INST]",
        "parameters": {"max_new_tokens": 600, "return_full_text": False}
    }
    
    # Retry logic (Free tier sometimes needs a second knock)
    for i in range(3):
        try:
            response = requests.post(HF_API_URL, headers=headers, json=payload)
            if response.status_code == 200:
                return response.json()[0]['generated_text']
            elif "loading" in response.text:
                print(f"⏳ Model loading... waiting 20s (Attempt {i+1}/3)")
                time.sleep(20)
            else:
                print(f"⚠️ API Error: {response.status_code} - {response.text}")
        except Exception as e:
            print(f"❌ Connection Error: {e}")
            time.sleep(5)
            
    return "Analysis Unavailable (API Timeout or Error)."

def send_intel_email(report_path, map_path):
    if not SENDER_EMAIL or not GMAIL_PASSWORD:
        print("⚠️ Email secrets missing. Skipping dispatch.")
        return

    print("📧 Dispatching Intelligence Brief to Inbox...")
    msg = MIMEMultipart()
    msg['From'] = SENDER_EMAIL
    msg['To'] = RECIPIENT_EMAIL
    msg['Subject'] = f"🚨 SATARK INTEL: {datetime.now().strftime('%B %Y')}"

    body = "Attached: Monthly Strategic Audit & Threat Map generated by SATARK V8.0."
    msg.attach(MIMEText(body, 'plain'))

    # Attach Report and Map
    for path in [report_path, map_path]:
        if os.path.exists(path):
            with open(path, "rb") as f:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(f.read())
                encoders.encode_base64(part)
                part.add_header("Content-Disposition", f"attachment; filename= {os.path.basename(path)}")
                msg.attach(part)

    try:
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(SENDER_EMAIL, GMAIL_PASSWORD)
            server.send_message(msg)
        print("✅ Email Sent Successfully.")
    except Exception as e:
        print(f"❌ Email Failed: {e}")

def run_monthly_audit():
    print("🚀 SATARK V8.0 (No-Billing Edition): STARTING...")
    
    # 2. DATA AGGREGATION
    report_dir = 'weekly_reports'
    files = glob.glob(f"{report_dir}/*.csv")
    if not files:
        print("⚠️ No weekly reports found.")
        return

    master_df = pd.concat([pd.read_csv(f) for f in files]).drop_duplicates(subset=['id'])
    print(f"📈 Total Unique Events for Audit: {len(master_df)}")
    
    # 3. LOSS CALCULATION
    master_df['ha'] = master_df['est_area_m2'] / 10000
    master_df['loss_inr'] = master_df.apply(lambda row: row['ha'] * 370000 if row['research_zone'] == "ZONE_A_NORTH" else row['ha'] * 58000, axis=1)

    # 4. MAP GENERATION
    plt.figure(figsize=(10, 8), facecolor='#121212')
    ax = plt.axes(); ax.set_facecolor("#121212")
    colors = master_df['research_zone'].map({'ZONE_A_NORTH':'#FF3131','ZONE_D_CENTRAL':'#FFBD03','ZONE_B_EAST':'#00E5FF','ZONE_C_SOUTH':'#70FF00'}).fillna('#FFFFFF')
    plt.scatter(master_df['lon'], master_df['lat'], s=master_df['ha']*4, c=colors, alpha=0.7)
    plt.title(f"SATARK THREAT MAP | {datetime.now().strftime('%B %Y')}", color='white')
    
    os.makedirs('monthly_audits', exist_ok=True)
    map_filename = f"monthly_audits/MAP_{datetime.now().strftime('%Y-%m')}.png"
    plt.savefig(map_filename, dpi=300, bbox_inches='tight'); plt.close()

    # 5. AI ANALYSIS (Using Hugging Face)
    total_loss_cr = master_df['loss_inr'].sum() / 10000000
    prompt = f"""
    ACT AS: Senior Policy Advisor.
    DATA: Month={datetime.now().strftime('%B %Y')}, Fires={len(master_df)}, Total Loss=INR {total_loss_cr:.2f} Crores.
    TASK: Write a 3-paragraph Strategic Memo. 
    1. Summarize the financial loss.
    2. Identify the urgency.
    3. Recommend one policy action.
    OUTPUT: Markdown text.
    """

    print("🤖 Mistral-7B is analyzing...")
    report_text = query_huggingface(prompt)

    # 6. ARCHIVE & SEND
    report_filename = f"monthly_audits/REPORT_{datetime.now().strftime('%Y-%m')}.md"
    with open(report_filename, "w") as f:
        f.write(f"# SATARK BRIEF // {datetime.now().strftime('%B %Y')}\n\n![Map]({os.path.basename(map_filename)})\n\n{report_text}")
    
    master_df.to_csv(f"monthly_audits/DATA_{datetime.now().strftime('%Y-%m')}.csv", index=False)
    
    # Send to your Gmail
    send_intel_email(report_filename, map_filename)

if __name__ == "__main__":
    run_monthly_audit()
